### ISSUE TITLE
Maybe add a figure of all colors in README

### ISSUE THREAD

**Issue by MengGuo** [adaldo/matplotlib-kthcolors#1]
So potential users like me can see what colors are available? :)

Good stuff, Antonio. 
/Meng

**Comment by adaldo** [comment]
Sebastian said the same :)
Thanks for the encouragement!
The preview is coming soon

**Comment by adaldo** [comment]
Should be ready now, so I am closing the issue.
Thanks for the feedback!!

/Antonio
